---
title: "LSU's Influence on Baton Rouge Crime Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(DT)
library(flexdashboard)
library(shiny)
library(htmlwidgets)
library(dygraphs)
library(tidyverse)
library(dplyr)
library(plotly)
```


```{r}
library(RSocrata)
library(tidyverse)
#calling package to read API and filter it

token <- "NDto4CJ4JBrcMyuBGCp4NiXs5"
#Security Token

OriginalData <- read.socrata("https://data.brla.gov/resource/5rji-ddnu.json", app_token = token)
#Converting into data frame

OriginalData %>%
  select('offense_date', 'crime', 'a_c', 'district') -> AllCrime
#filtering API down to needed data

AllCrime %>%
  filter(str_detect(offense_date, "2018")) %>% 
  mutate(offense_date = lubridate::ymd(offense_date)) -> BRCrime



#LSUFootball Upload
LSUFootball <- read_csv(here::here("Data","2018LSUFootballSchedule.csv"),
                        col_types = cols(Date = col_date(format = "%m/%d/%Y"), 
                                         EndTime = col_skip(), GameAttendance = col_number(), 
                                         LSUPoints = col_number(), OpponentPoints = col_number(), 
                                         SpecialEvent = col_logical(), StartTime = col_skip()))
#mean(LSUFootball$LSUPoints)
#meanfunction
full_join(BRCrime, LSUFootball, by = c("offense_date" = "Date")) -> JoinedData
```


Row {data-width=600}
-----------------------------------------------------------------------
### Daily Crime Counts Table

```{r}
    count(JoinedData, offense_date, Sport) %>%  
      group_by(Sport) %>% 
      ggplot(mapping = aes(x = offense_date, y = n)) +
      geom_line(color = 'purple', size = 1)+ 
      ggtitle("Crimes for 2018", "Count of Crimes per Day in 2018") +
      xlab("Date Committed") +
      ylab("Total Crimes") +
      geom_hline(yintercept = 125, color = 'gold', size = 1) -> DailyCrimefor2018
ggplotly(DailyCrimefor2018)

```


### Total Crimes Committed for LSU Opponnents

```{r}
ggplot(data=subset(JoinedData, !is.na(LSUPoints)), mapping = aes(x= reorder(Opponent, offense_date), fill=Outcome)) +
  geom_bar()+
  theme(axis.text.x = element_text(angle = 45))+
  ggtitle("Count of Crimes by LSU Opponents", "In Order of LSU 2018 Season")+
  geom_hline(yintercept = 125, color = 'gold', size = 1)+
  xlab("Opponent Universities")+
  ylab("Total Crime") -> CrimeByOpponent

ggplotly(CrimeByOpponent)
```

Row {data-width=400}
-----------------------------------------------------------------------

### Audience Influence on Outcome
```{r}

ggplot(data = LSUFootball, mapping = aes(x = GameAttendance, y = LSUPoints)) +
  geom_point(size = 4, position = "jitter",color = 'purple') +
  ggtitle("LSU Points Scored by Game Attendance", "Colored by Outcome")+
  geom_hline(yintercept = 33, color = 'gold', size = 1)+
  geom_vline(xintercept = 90340, color = 'gold', size = 1)+
  xlab("Attendance")+
  ylab("LSU Points Scored")+
  scale_x_continuous(labels = scales::comma)+
  theme(axis.text.x = element_text(angle = 90))+
  facet_wrap(~Outcome) -> AudienceOutcome
  
ggplotly(AudienceOutcome)
```

### Gameday vs Non Gameday Crime Counts

```{r}
  count(JoinedData, offense_date, Sport, crime) %>%  
  group_by(Sport, crime) %>% 
  summarise(AverageRate = mean(n)) %>% 
  ggplot(mapping = aes(x = crime, y = AverageRate)) +
  geom_col(fill = 'purple')+
  theme(axis.text.x = element_text(angle = 90))+
  ggtitle("Daily Crime Count by Type", "Faceted by LSU vs NonLSU Dates") +
  xlab("Crime Type") +
  ylab("Crime Rate")+
  facet_wrap(~Sport) -> GamedayvsNonGameday
ggplotly(GamedayvsNonGameday)
```

